name: Timestamp Example

on: [push]

jobs:
  use-timestamp:
    runs-on: ubuntu-latest
    steps:

      - name: Run tests
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          mkdir -p test-results
          touch test-results/$TIMESTAMP-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/
