name: Timestamp Example

on: [push]

jobs:
  use-timestamp:
    runs-on: ubuntu-latest
    steps:
    
      - name: Run tests
        run: |
          mkdir -p test-results
          touch test-results/result.xml
      - name: add timestamp
        run: |
          echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results_${{ env.TIMESTAMP }}
          path: test-results/
          

