name: Timestamp Example

on: [push]

jobs:
  use-timestamp:
    runs-on: ubuntu-latest
    steps:

      - name: Run tests
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          mkdir -p test-results-$TIMESTAMP
          touch test-results-$TIMESTAMP/$TIMESTAMP-results.xml
          ls -lrt
          ls -d
